[2025-02-26T14:21:14.633+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T14:21:14.656+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2021-12-13T00:00:00+00:00 [queued]>
[2025-02-26T14:21:14.675+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.second_task scheduled__2021-12-13T00:00:00+00:00 [queued]>
[2025-02-26T14:21:14.675+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-26T14:21:14.703+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2021-12-13 00:00:00+00:00
[2025-02-26T14:21:14.719+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5647) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-26T14:21:14.721+0000] {standard_task_runner.py:72} INFO - Started process 5754 to run task
[2025-02-26T14:21:14.724+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'second_task', 'scheduled__2021-12-13T00:00:00+00:00', '--job-id', '432', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpdpv7x7zt']
[2025-02-26T14:21:14.731+0000] {standard_task_runner.py:105} INFO - Job 432: Subtask second_task
[2025-02-26T14:21:14.804+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.second_task scheduled__2021-12-13T00:00:00+00:00 [running]> on host 25887b48f6fb
[2025-02-26T14:21:14.930+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-13T00:00:00+00:00'
[2025-02-26T14:21:14.932+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-26T14:21:14.933+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-26T14:21:14.934+0000] {logging_mixin.py:190} INFO - Current task name:second_task state:running start_date:2025-02-26 14:21:14.656854+00:00
[2025-02-26T14:21:14.934+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag and current dag run status:running
[2025-02-26T14:21:14.934+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T14:21:14.935+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-26T14:21:14.936+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-02-26T14:21:14.961+0000] {subprocess.py:99} INFO - Output:
[2025-02-26T14:21:14.965+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1!
[2025-02-26T14:21:14.966+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-26T14:21:15.014+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T14:21:15.015+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=second_task, run_id=scheduled__2021-12-13T00:00:00+00:00, execution_date=20211213T000000, start_date=20250226T142114, end_date=20250226T142115
[2025-02-26T14:21:15.049+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-26T14:21:15.050+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-26T14:21:15.051+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag queued_at:2025-02-26 14:21:10.381608+00:00
[2025-02-26T14:21:15.051+0000] {logging_mixin.py:190} INFO - Task hostname:25887b48f6fb operator:BashOperator
[2025-02-26T14:21:15.097+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-26T14:21:15.108+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
