[2025-03-04T07:03:25.713+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T07:03:25.724+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-04T07:03:25.729+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-04T07:03:25.729+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-04T07:03:25.739+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-01 00:00:00+00:00
[2025-03-04T07:03:25.745+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-04T07:03:25.746+0000] {standard_task_runner.py:72} INFO - Started process 292 to run task
[2025-03-04T07:03:25.744+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'backfill__2025-03-01T00:00:00+00:00', '--job-id', '250', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpb2b0ifyu']
[2025-03-04T07:03:25.746+0000] {standard_task_runner.py:105} INFO - Job 250: Subtask task1
[2025-03-04T07:03:25.779+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [running]> on host 6a5bb1760b4d
[2025-03-04T07:03:25.847+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naveen' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v01' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2025-03-01T00:00:00+00:00'
[2025-03-04T07:03:25.848+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T07:03:25.850+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-04T07:03:25.850+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-03-04T07:03:25.858+0000] {subprocess.py:99} INFO - Output:
[2025-03-04T07:03:25.860+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-03-04T07:03:25.860+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-04T07:03:25.892+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T07:03:25.892+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v01, task_id=task1, run_id=backfill__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250304T070325, end_date=20250304T070325
[2025-03-04T07:03:25.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T07:03:25.990+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T07:03:25.993+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-05T11:15:22.637+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T11:15:22.651+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-05T11:15:22.657+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-05T11:15:22.657+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-05T11:15:22.668+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-01 00:00:00+00:00
[2025-03-05T11:15:22.675+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=344) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T11:15:22.674+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'backfill__2025-03-01T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpoykkf97s']
[2025-03-05T11:15:22.676+0000] {standard_task_runner.py:72} INFO - Started process 348 to run task
[2025-03-05T11:15:22.676+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask task1
[2025-03-05T11:15:22.718+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 backfill__2025-03-01T00:00:00+00:00 [running]> on host 5838e5832ebd
[2025-03-05T11:15:22.781+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naveen' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v01' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2025-03-01T00:00:00+00:00'
[2025-03-05T11:15:22.782+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T11:15:22.784+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-05T11:15:22.784+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-03-05T11:15:22.795+0000] {subprocess.py:99} INFO - Output:
[2025-03-05T11:15:22.796+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-03-05T11:15:22.796+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-05T11:15:22.816+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T11:15:22.816+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v01, task_id=task1, run_id=backfill__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250305T111522, end_date=20250305T111522
[2025-03-05T11:15:22.890+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T11:15:22.932+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T11:15:22.937+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
