[2025-03-06T04:50:05.266+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-06T04:50:05.286+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [queued]>
[2025-03-06T04:50:05.294+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [queued]>
[2025-03-06T04:50:05.294+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-06T04:50:05.306+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-05 00:00:00+00:00
[2025-03-06T04:50:05.314+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2025-03-05T00:00:00+00:00', '--job-id', '611', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpd_gviy9r']
[2025-03-06T04:50:05.315+0000] {standard_task_runner.py:105} INFO - Job 611: Subtask second_task
[2025-03-06T04:50:05.316+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1383155) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-06T04:50:05.317+0000] {standard_task_runner.py:72} INFO - Started process 1383191 to run task
[2025-03-06T04:50:05.355+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [running]> on host 25887b48f6fb
[2025-03-06T04:50:05.442+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T00:00:00+00:00'
[2025-03-06T04:50:05.443+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-06T04:50:05.444+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-06T04:50:05.444+0000] {logging_mixin.py:190} INFO - Current task name:second_task state:running start_date:2025-03-06 04:50:05.287280+00:00
[2025-03-06T04:50:05.444+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag_v1 and current dag run status:running
[2025-03-06T04:50:05.444+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-06T04:50:05.444+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-06T04:50:05.445+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-03-06T04:50:05.458+0000] {subprocess.py:99} INFO - Output:
[2025-03-06T04:50:05.459+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1!
[2025-03-06T04:50:05.459+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-06T04:50:05.485+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-06T04:50:05.486+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2025-03-05T00:00:00+00:00, execution_date=20250305T000000, start_date=20250306T045005, end_date=20250306T045005
[2025-03-06T04:50:05.512+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-06T04:50:05.513+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-06T04:50:05.513+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag_v1 queued_at:2025-03-06 04:50:03.210628+00:00
[2025-03-06T04:50:05.513+0000] {logging_mixin.py:190} INFO - Task hostname:25887b48f6fb operator:BashOperator
[2025-03-06T04:50:05.531+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-06T04:50:05.544+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T04:50:05.546+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-07T10:44:12.219+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [queued]>
[2025-03-07T10:44:12.226+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [queued]>
[2025-03-07T10:44:12.226+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-03-07T10:44:12.240+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2025-03-05 00:00:00+00:00
[2025-03-07T10:44:12.245+0000] {standard_task_runner.py:57} INFO - Started process 406 to run task
[2025-03-07T10:44:12.248+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2025-03-05T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8hsf5nvi']
[2025-03-07T10:44:12.252+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask second_task
[2025-03-07T10:44:12.303+0000] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-05T00:00:00+00:00 [running]> on host 93934f8e361f
[2025-03-07T10:44:12.383+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T00:00:00+00:00'
[2025-03-07T10:44:12.384+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-07T10:44:12.384+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-03-07T10:44:12.395+0000] {subprocess.py:86} INFO - Output:
[2025-03-07T10:44:12.399+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2025-03-07T10:44:12.400+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-07T10:44:12.428+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, execution_date=20250305T000000, start_date=20250307T104412, end_date=20250307T104412
[2025-03-07T10:44:12.461+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-07T10:44:12.488+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
