[2025-03-07T05:00:10.802+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T05:00:10.823+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [queued]>
[2025-03-07T05:00:10.835+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [queued]>
[2025-03-07T05:00:10.835+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-07T05:00:10.849+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-06 00:00:00+00:00
[2025-03-07T05:00:10.858+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2025-03-06T00:00:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpz8ijy5xq']
[2025-03-07T05:00:10.859+0000] {standard_task_runner.py:105} INFO - Job 615: Subtask second_task
[2025-03-07T05:00:10.860+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1709078) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-07T05:00:10.861+0000] {standard_task_runner.py:72} INFO - Started process 1709141 to run task
[2025-03-07T05:00:10.902+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [running]> on host 25887b48f6fb
[2025-03-07T05:00:10.969+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-06T00:00:00+00:00'
[2025-03-07T05:00:10.970+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-07T05:00:10.970+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-07T05:00:10.971+0000] {logging_mixin.py:190} INFO - Current task name:second_task state:running start_date:2025-03-07 05:00:10.824278+00:00
[2025-03-07T05:00:10.971+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag_v1 and current dag run status:running
[2025-03-07T05:00:10.971+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-07T05:00:10.971+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-07T05:00:10.972+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-03-07T05:00:10.984+0000] {subprocess.py:99} INFO - Output:
[2025-03-07T05:00:10.986+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1!
[2025-03-07T05:00:10.987+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-07T05:00:11.015+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-07T05:00:11.015+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, run_id=scheduled__2025-03-06T00:00:00+00:00, execution_date=20250306T000000, start_date=20250307T050010, end_date=20250307T050011
[2025-03-07T05:00:11.040+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-07T05:00:11.040+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-07T05:00:11.040+0000] {logging_mixin.py:190} INFO - Dag name:our_first_dag_v1 queued_at:2025-03-07 05:00:08.901047+00:00
[2025-03-07T05:00:11.040+0000] {logging_mixin.py:190} INFO - Task hostname:25887b48f6fb operator:BashOperator
[2025-03-07T05:00:11.075+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T05:00:11.093+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-07T05:00:11.098+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-07T10:44:12.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [queued]>
[2025-03-07T10:44:12.228+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [queued]>
[2025-03-07T10:44:12.228+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-03-07T10:44:12.242+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2025-03-06 00:00:00+00:00
[2025-03-07T10:44:12.250+0000] {standard_task_runner.py:57} INFO - Started process 408 to run task
[2025-03-07T10:44:12.256+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'second_task', 'scheduled__2025-03-06T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpc9lkoat9']
[2025-03-07T10:44:12.259+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask second_task
[2025-03-07T10:44:12.315+0000] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v1.second_task scheduled__2025-03-06T00:00:00+00:00 [running]> on host 93934f8e361f
[2025-03-07T10:44:12.385+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-06T00:00:00+00:00'
[2025-03-07T10:44:12.386+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-07T10:44:12.386+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2025-03-07T10:44:12.395+0000] {subprocess.py:86} INFO - Output:
[2025-03-07T10:44:12.397+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2025-03-07T10:44:12.398+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-07T10:44:12.424+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=second_task, execution_date=20250306T000000, start_date=20250307T104412, end_date=20250307T104412
[2025-03-07T10:44:12.468+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-07T10:44:12.493+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
