[2025-03-10T05:10:41.502+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-10T05:10:41.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-03-09T00:00:00+00:00 [queued]>
[2025-03-10T05:10:41.508+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-03-10T05:10:41.518+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-03-09 00:00:00+00:00
[2025-03-10T05:10:41.521+0000] {standard_task_runner.py:57} INFO - Started process 3162 to run task
[2025-03-10T05:10:41.524+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2025-03-09T00:00:00+00:00', '--job-id', '554', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator.py', '--cfg-path', '/tmp/tmpclpxz926']
[2025-03-10T05:10:41.526+0000] {standard_task_runner.py:85} INFO - Job 554: Subtask insert_into_table
[2025-03-10T05:10:41.566+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-03-09T00:00:00+00:00 [running]> on host 4ed652ed1873
[2025-03-10T05:10:41.632+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T00:00:00+00:00'
[2025-03-10T05:10:41.632+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2025-03-09', 'dag_with_postgres_operator_v03')
        
[2025-03-10T05:10:41.642+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-10T05:10:41.651+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-10T05:10:41.655+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2025-03-09', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-03-10T05:10:41.659+0000] {sql.py:427} INFO - Rows affected: 1
[2025-03-10T05:10:41.667+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20250309T000000, start_date=20250310T051041, end_date=20250310T051041
[2025-03-10T05:10:41.695+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-10T05:10:41.708+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
